"""Files for the local Mosquitto: PSK file and bridge config (Broker_Specs §4).

Written atomically; the watcher in the broker container reloads on a PSK
change and restarts Mosquitto on a bridge change.
"""

import os
from pathlib import Path

DEVICE_OUT = ("status", "telemetry", "event", "cmd/ack", "config/state")


def _write_atomic(path: Path, content: str, mode: int = 0o640) -> bool:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists() and path.read_text() == content:
        return False
    tmp = path.with_name(path.name + ".tmp")
    tmp.write_text(content)
    os.chmod(tmp, mode)
    tmp.replace(path)
    return True


def write_psk(broker_dir: Path, devices: list[dict]) -> bool:
    """`identity:hexkey` per device, from `down/keys`."""
    content = "".join(f"{d['id']}:{d['psk']}\n" for d in devices)
    return _write_atomic(broker_dir / "psk", content)


def render_bridge(hub_id: str, host: str, port: int, psk: str, device_ids: list[str]) -> str:
    lines = [
        "# Generated by the hub agent. Do not edit.",
        "connection cloud",
        f"address {host}:{port}",
        "bridge_protocol_version mqttv311",
        f"bridge_identity {hub_id}",
        f"bridge_psk {psk}",
        "bridge_tls_version tlsv1.2",
        f"remote_clientid {hub_id}",
        "local_clientid bridge-cloud",
        "cleansession false",
        "try_private true",
        "start_type automatic",
        "restart_timeout 5 60",
        "keepalive_interval 60",
        "notifications true",
        f"notification_topic mc/hub/v1/{hub_id}/up/bridge",
        "",
        "# device → cloud",
        *[f"topic mc/v1/+/{s} out 1" for s in DEVICE_OUT],
        f"topic mc/hub/v1/{hub_id}/up/# out 1",
        "",
        "# cloud → hub: exact topics only",
        f"topic mc/hub/v1/{hub_id}/down/snapshot in 1",
        f"topic mc/hub/v1/{hub_id}/down/keys in 1",
    ]
    for dev in sorted(device_ids):
        lines += [f"topic mc/v1/{dev}/cmd in 1", f"topic mc/v1/{dev}/config/desired in 1"]
    return "\n".join(lines) + "\n"


def write_bridge(broker_dir: Path, content: str) -> bool:
    # 0640 + shared group mcbroker: Mosquitto (another user) must read it.
    return _write_atomic(broker_dir / "conf.d" / "bridge.conf", content, 0o640)


def remove_bridge(broker_dir: Path) -> None:
    """Back to unenrolled: no bridge, no device keys."""
    bridge = broker_dir / "conf.d" / "bridge.conf"
    if bridge.exists():
        bridge.unlink()
    _write_atomic(broker_dir / "psk", "")
