"""gateways and downlink (D33)

Revision ID: a24a6c83f64a
Revises: 804fd5a2d693
Create Date: 2026-09-29 15:13:32.359274
"""

from alembic import op
import sqlalchemy as sa
import mc_api.db.types


revision = 'a24a6c83f64a'
down_revision = '804fd5a2d693'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gateway_enrollments',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('secret_sha256', sa.String(length=64), nullable=False),
    sa.Column('user_code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('claimed_household_id', sa.String(length=26), nullable=True),
    sa.Column('claimed_by', sa.String(length=128), nullable=True),
    sa.Column('gateway_id', sa.String(length=24), nullable=True),
    sa.Column('credential_enc', sa.Text(), nullable=True),
    sa.Column('consumed_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_poll_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('arch', sa.String(length=16), nullable=True),
    sa.Column('adapters', sa.JSON(), nullable=True),
    sa.Column('created_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('gateway_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_gateway_enrollments_user_code_hash'), ['user_code_hash'], unique=False)

    op.create_table('gateways',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('credential_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('connected_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('disconnected_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_outage_s', sa.Integer(), nullable=False),
    sa.Column('last_state', sa.JSON(), nullable=True),
    sa.Column('last_state_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('lan_host_override', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=32), nullable=True),
    sa.Column('adapters', sa.JSON(), nullable=True),
    sa.Column('snapshot_rev_applied', sa.Integer(), nullable=False),
    sa.Column('keys_rev_applied', sa.Integer(), nullable=False),
    sa.Column('last_up_seq', sa.Integer(), nullable=False),
    sa.Column('created_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id')
    )
    op.create_table('downlink',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('gateway_id', sa.String(length=24), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('created_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sent_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('acked_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('result', sa.String(length=12), nullable=True),
    sa.Column('error', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['gateway_id'], ['gateways.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('downlink', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_downlink_acked_at'), ['acked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_downlink_gateway_id'), ['gateway_id'], unique=False)

    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_sent_at'))

    op.drop_table('outbox')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sent_at', mc_api.db.types.UTCDateTime(timezone=True), nullable=True))

    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('adapter', sa.String(length=16), nullable=False,
                                      server_default='esp32-mqtt'))

    # ### end Alembic commands ###
    # Devices keyed on the old cloud broker or hub must be re-paired to a gateway.
    op.execute("UPDATE devices SET gateway = 'none' WHERE gateway <> 'gateway'")
    op.execute("UPDATE commands SET origin = 'api' WHERE origin = 'cloud'")
    op.execute("UPDATE commands SET origin = 'gateway' WHERE origin = 'hub'")
    op.execute("UPDATE rule_executions SET origin = 'api' WHERE origin = 'cloud'")
    op.execute("UPDATE rule_executions SET origin = 'gateway' WHERE origin = 'hub'")
    op.execute("UPDATE readings SET ts_source = 'gateway' WHERE ts_source = 'server'")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('adapter')

    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_column('sent_at')

    op.create_table('outbox',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('topic', sa.VARCHAR(length=255), nullable=False),
    sa.Column('payload', sa.TEXT(), nullable=True),
    sa.Column('qos', sa.INTEGER(), nullable=False),
    sa.Column('retain', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('sent_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_sent_at'), ['sent_at'], unique=False)

    with op.batch_alter_table('downlink', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_downlink_gateway_id'))
        batch_op.drop_index(batch_op.f('ix_downlink_acked_at'))

    op.drop_table('downlink')
    op.drop_table('gateways')
    with op.batch_alter_table('gateway_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_gateway_enrollments_user_code_hash'))

    op.drop_table('gateway_enrollments')
    # ### end Alembic commands ###
