#!/usr/bin/env python3
"""Extracts the JSON examples of contracts/mqtt.md into a C header for the unit tests.

Only inbound documents (what the device must parse) are extracted: `config/desired`
(§6.1) and `cmd` (§5.1). Examples containing "…" are placeholders and skipped.

The BLE session vectors (contracts/ble_vectors.json) become `ble_vectors.h`.
"""

import json
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[2]
text = (root / "contracts" / "mqtt.md").read_text()
blocks = re.findall(r"```json\n(.*?)```", text, re.S)

desired, commands = [], []
for raw in blocks:
    if "…" in raw:
        continue
    doc = json.loads(raw)
    compact = json.dumps(doc, separators=(",", ":"), ensure_ascii=False)
    if "action" in doc and "id" in doc:
        commands.append(compact)
    elif "slots" in doc and "rev" in doc and "result" not in doc:
        desired.append(compact)


def c_array(name: str, items: list[str]) -> str:
    body = ",\n".join('\t"' + i.replace("\\", "\\\\").replace('"', '\\"') + '"' for i in items)
    return f"static const char *const {name}[] = {{\n{body}\n}};\n#define {name.upper()}_N {len(items)}\n"


out = Path(sys.argv[1])
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("/* generated by scripts/gen_contract_examples.py: do not edit */\n"
               + c_array("example_desired", desired) + c_array("example_cmds", commands))
print(f"{len(desired)} config and {len(commands)} command examples -> {out}")


# --- BLE vectors ----------------------------------------------------------------------------

v = json.loads((root / "contracts" / "ble_vectors.json").read_text())


def frames_c(name: str, frames: list[dict]) -> str:
    rows = ",\n".join(f'\t{{{"true" if f["dir"] == "app->dev" else "false"}, "{f["frame"]}"}}'
                      for f in frames)
    return f"static const struct vframe {name}[] = {{\n{rows}\n}};\n#define {name.upper()}_N {len(frames)}\n"


header = "/* generated by scripts/gen_contract_examples.py: do not edit */\nstruct vframe {\n\tbool to_dev;\n\tconst char *hex;\n};\n"
for key in ("pop", "app_private", "device_private", "nonce_d", "mac_dev", "k_enc", "k_mac",
            "factory_page"):
    header += f'static const char vec_{key}[] = "{v[key]}";\n'
header += frames_c("vec_frames", v["frames"]) + frames_c("vec_ops_frames", v["ops_frames"])
(out.parent / "ble_vectors.h").write_text(header)
print(f"{len(v['frames'])} + {len(v['ops_frames'])} BLE frames -> {out.parent / 'ble_vectors.h'}")
