#!/usr/bin/env python3
"""Extracts the JSON examples of contracts/mqtt.md into a C header for the unit tests.

Only inbound documents (what the device must parse) are extracted: `config/desired`
(§6.1) and `cmd` (§5.1). Examples containing "…" are placeholders and skipped.
"""

import json
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parents[2]
text = (root / "contracts" / "mqtt.md").read_text()
blocks = re.findall(r"```json\n(.*?)```", text, re.S)

desired, commands = [], []
for raw in blocks:
    if "…" in raw:
        continue
    doc = json.loads(raw)
    compact = json.dumps(doc, separators=(",", ":"), ensure_ascii=False)
    if "action" in doc and "id" in doc:
        commands.append(compact)
    elif "slots" in doc and "rev" in doc and "result" not in doc:
        desired.append(compact)


def c_array(name: str, items: list[str]) -> str:
    body = ",\n".join('\t"' + i.replace("\\", "\\\\").replace('"', '\\"') + '"' for i in items)
    return f"static const char *const {name}[] = {{\n{body}\n}};\n#define {name.upper()}_N {len(items)}\n"


out = Path(sys.argv[1])
out.parent.mkdir(parents=True, exist_ok=True)
out.write_text("/* generated by scripts/gen_contract_examples.py: do not edit */\n"
               + c_array("example_desired", desired) + c_array("example_cmds", commands))
print(f"{len(desired)} config and {len(commands)} command examples -> {out}")
