"""drop hub tables (D33)

Revision ID: 804fd5a2d693
Revises: d9b8b6a66647
Create Date: 2026-09-29 15:02:06.987987
"""

from alembic import op
import sqlalchemy as sa
import mc_server.db.types
from sqlalchemy.dialects import sqlite

revision = '804fd5a2d693'
down_revision = 'd9b8b6a66647'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hubs')
    with op.batch_alter_table('hub_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hub_enrollments_user_code_hash'))

    op.drop_table('hub_enrollments')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hub_enrollments',
    sa.Column('id', sa.VARCHAR(length=26), nullable=False),
    sa.Column('secret_sha256', sa.VARCHAR(length=64), nullable=False),
    sa.Column('user_code_hash', sa.VARCHAR(length=64), nullable=False),
    sa.Column('expires_at', sa.DATETIME(), nullable=False),
    sa.Column('claimed_household_id', sa.VARCHAR(length=26), nullable=True),
    sa.Column('claimed_by', sa.VARCHAR(length=128), nullable=True),
    sa.Column('hub_id', sa.VARCHAR(length=24), nullable=True),
    sa.Column('consumed_at', sa.DATETIME(), nullable=True),
    sa.Column('last_poll_at', sa.DATETIME(), nullable=True),
    sa.Column('ip', sa.VARCHAR(length=64), nullable=True),
    sa.Column('agent_version', sa.VARCHAR(length=32), nullable=True),
    sa.Column('arch', sa.VARCHAR(length=16), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hub_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hub_enrollments_user_code_hash'), ['user_code_hash'], unique=False)

    op.create_table('hubs',
    sa.Column('id', sa.VARCHAR(length=24), nullable=False),
    sa.Column('household_id', sa.VARCHAR(length=26), nullable=False),
    sa.Column('psk_enc', sa.TEXT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=16), nullable=False),
    sa.Column('bridge_connected', sa.BOOLEAN(), nullable=False),
    sa.Column('bridge_changed_at', sa.DATETIME(), nullable=True),
    sa.Column('last_outage_s', sa.INTEGER(), nullable=False),
    sa.Column('last_state', sqlite.JSON(), nullable=True),
    sa.Column('last_state_at', sa.DATETIME(), nullable=True),
    sa.Column('lan_host_override', sa.VARCHAR(length=255), nullable=True),
    sa.Column('snapshot_rev_applied', sa.INTEGER(), nullable=False),
    sa.Column('keys_rev_applied', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id')
    )
    # ### end Alembic commands ###
