"""initial schema

Revision ID: d9b8b6a66647
Revises: 
Create Date: 2026-09-28 15:57:04.012629
"""

from alembic import op
import sqlalchemy as sa
import mc_server.db.types


revision = 'd9b8b6a66647'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=True),
    sa.Column('actor', sa.String(length=128), nullable=True),
    sa.Column('action', sa.String(length=40), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('ts', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_household_id'), ['household_id'], unique=False)

    op.create_table('households',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('battery_low_mv', sa.Integer(), nullable=False),
    sa.Column('snapshot_rev', sa.Integer(), nullable=False),
    sa.Column('keys_rev', sa.Integer(), nullable=False),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hub_enrollments',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('secret_sha256', sa.String(length=64), nullable=False),
    sa.Column('user_code_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('claimed_household_id', sa.String(length=26), nullable=True),
    sa.Column('claimed_by', sa.String(length=128), nullable=True),
    sa.Column('hub_id', sa.String(length=24), nullable=True),
    sa.Column('consumed_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_poll_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('agent_version', sa.String(length=32), nullable=True),
    sa.Column('arch', sa.String(length=16), nullable=True),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('hub_enrollments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hub_enrollments_user_code_hash'), ['user_code_hash'], unique=False)

    op.create_table('outbox',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('qos', sa.Integer(), nullable=False),
    sa.Column('retain', sa.Boolean(), nullable=False),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('sent_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_sent_at'), ['sent_at'], unique=False)

    op.create_table('users',
    sa.Column('uid', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('first_seen_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('alerts',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('subject_type', sa.String(length=10), nullable=False),
    sa.Column('subject_id', sa.String(length=26), nullable=False),
    sa.Column('subject_name', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.String(length=8), nullable=False),
    sa.Column('opened_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('resolved_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('acked_by', sa.String(length=128), nullable=True),
    sa.Column('acked_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_household_id'), ['household_id'], unique=False)
        batch_op.create_index('uq_open_alert', ['household_id', 'kind', 'subject_id'], unique=True, postgresql_where=sa.text('resolved_at IS NULL'), sqlite_where=sa.text('resolved_at IS NULL'))

    op.create_table('devices',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('psk_enc', sa.Text(), nullable=True),
    sa.Column('gateway', sa.String(length=8), nullable=False),
    sa.Column('hw_mac', sa.String(length=17), nullable=True),
    sa.Column('fw', sa.String(length=32), nullable=True),
    sa.Column('board', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('last_seen_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_expected_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('wake_interval_s', sa.Integer(), nullable=False),
    sa.Column('batt_mv', sa.Integer(), nullable=True),
    sa.Column('rssi', sa.Integer(), nullable=True),
    sa.Column('last_seq', sa.Integer(), nullable=True),
    sa.Column('last_boot', sa.Integer(), nullable=True),
    sa.Column('desired_rev', sa.Integer(), nullable=False),
    sa.Column('desired_config', sa.JSON(), nullable=True),
    sa.Column('reported_rev', sa.Integer(), nullable=False),
    sa.Column('reported_config', sa.JSON(), nullable=True),
    sa.Column('rejected_rev', sa.Integer(), nullable=True),
    sa.Column('config_error', sa.JSON(), nullable=True),
    sa.Column('sensor_error_streak', sa.JSON(), nullable=True),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_household_id'), ['household_id'], unique=False)

    op.create_table('hubs',
    sa.Column('id', sa.String(length=24), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('psk_enc', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('bridge_connected', sa.Boolean(), nullable=False),
    sa.Column('bridge_changed_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_outage_s', sa.Integer(), nullable=False),
    sa.Column('last_state', sa.JSON(), nullable=True),
    sa.Column('last_state_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('lan_host_override', sa.String(length=255), nullable=True),
    sa.Column('snapshot_rev_applied', sa.Integer(), nullable=False),
    sa.Column('keys_rev_applied', sa.Integer(), nullable=False),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id')
    )
    op.create_table('invites',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('expires_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('used_by', sa.String(length=128), nullable=True),
    sa.Column('used_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code_hash')
    )
    op.create_table('memberships',
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('user_uid', sa.String(length=128), nullable=False),
    sa.Column('role', sa.String(length=10), nullable=False),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('household_id', 'user_uid')
    )
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.create_index('ix_memberships_user', ['user_uid'], unique=False)
        batch_op.create_index('uq_one_owner', ['household_id'], unique=True, postgresql_where=sa.text("role = 'owner'"), sqlite_where=sa.text("role = 'owner'"))

    op.create_table('push_tokens',
    sa.Column('token', sa.String(length=512), nullable=False),
    sa.Column('user_uid', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=16), nullable=True),
    sa.Column('updated_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_uid'], ['users.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token')
    )
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_push_tokens_user_uid'), ['user_uid'], unique=False)

    op.create_table('rule_executions',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('rule_id', sa.String(length=26), nullable=False),
    sa.Column('plant_id', sa.String(length=26), nullable=False),
    sa.Column('ts', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('reading_ref', sa.JSON(), nullable=True),
    sa.Column('decision', sa.String(length=5), nullable=False),
    sa.Column('skip_reason', sa.String(length=20), nullable=True),
    sa.Column('command_id', sa.String(length=26), nullable=True),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rule_executions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rule_executions_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rule_executions_rule_id'), ['rule_id'], unique=False)

    op.create_table('commands',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('device_id', sa.String(length=24), nullable=False),
    sa.Column('plant_id', sa.String(length=26), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('args', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('reason', sa.String(length=32), nullable=True),
    sa.Column('source', sa.String(length=8), nullable=False),
    sa.Column('origin', sa.String(length=8), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('rule_id', sa.String(length=26), nullable=True),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('exp', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('delivered_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('ends_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cancel_of', sa.String(length=26), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.create_index('ix_commands_device_status', ['device_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_commands_household_id'), ['household_id'], unique=False)

    op.create_table('config_revisions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=24), nullable=False),
    sa.Column('rev', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('body', sa.JSON(), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('error', sa.JSON(), nullable=True),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('config_revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_config_revisions_device_id'), ['device_id'], unique=False)

    op.create_table('device_events',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=24), nullable=False),
    sa.Column('ts', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=24), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.create_index('ix_events_device_ts', ['device_id', 'ts'], unique=False)

    op.create_table('health_reports',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=24), nullable=False),
    sa.Column('ts', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('batt_mv', sa.Integer(), nullable=False),
    sa.Column('rssi', sa.Integer(), nullable=False),
    sa.Column('wake', sa.String(length=12), nullable=False),
    sa.Column('cycle_ms', sa.Integer(), nullable=True),
    sa.Column('wifi_ms', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_reports', schema=None) as batch_op:
        batch_op.create_index('ix_health_device_ts', ['device_id', 'ts'], unique=False)

    op.create_table('plants',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sensor_device_id', sa.String(length=24), nullable=True),
    sa.Column('sensor_slot', sa.Integer(), nullable=True),
    sa.Column('pump_device_id', sa.String(length=24), nullable=True),
    sa.Column('pump_slot', sa.Integer(), nullable=True),
    sa.Column('archived_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pump_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sensor_device_id'], ['devices.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plants_household_id'), ['household_id'], unique=False)

    op.create_table('readings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=24), nullable=False),
    sa.Column('slot', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.String(length=26), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('raw', sa.Integer(), nullable=True),
    sa.Column('error', sa.String(length=20), nullable=True),
    sa.Column('ts', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.Column('ts_source', sa.String(length=8), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index('ix_readings_device_slot_ts', ['device_id', 'slot', 'ts'], unique=False)
        batch_op.create_index('ix_readings_plant_ts', ['plant_id', 'ts'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.String(length=26), nullable=False),
    sa.Column('household_id', sa.String(length=26), nullable=False),
    sa.Column('plant_id', sa.String(length=26), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('water_s', sa.Integer(), nullable=False),
    sa.Column('cooldown_s', sa.Integer(), nullable=False),
    sa.Column('max_per_day', sa.Integer(), nullable=False),
    sa.Column('quiet_from', sa.String(length=5), nullable=True),
    sa.Column('quiet_to', sa.String(length=5), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=True),
    sa.Column('updated_at', mc_server.db.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_household_id'), ['household_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_plant_id'), ['plant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_plant_id'))
        batch_op.drop_index(batch_op.f('ix_rules_household_id'))

    op.drop_table('rules')
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index('ix_readings_plant_ts')
        batch_op.drop_index('ix_readings_device_slot_ts')

    op.drop_table('readings')
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plants_household_id'))

    op.drop_table('plants')
    with op.batch_alter_table('health_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_health_device_ts')

    op.drop_table('health_reports')
    with op.batch_alter_table('device_events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_device_ts')

    op.drop_table('device_events')
    with op.batch_alter_table('config_revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_config_revisions_device_id'))

    op.drop_table('config_revisions')
    with op.batch_alter_table('commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_commands_household_id'))
        batch_op.drop_index('ix_commands_device_status')

    op.drop_table('commands')
    with op.batch_alter_table('rule_executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rule_executions_rule_id'))
        batch_op.drop_index(batch_op.f('ix_rule_executions_household_id'))

    op.drop_table('rule_executions')
    with op.batch_alter_table('push_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_push_tokens_user_uid'))

    op.drop_table('push_tokens')
    with op.batch_alter_table('memberships', schema=None) as batch_op:
        batch_op.drop_index('uq_one_owner', postgresql_where=sa.text("role = 'owner'"), sqlite_where=sa.text("role = 'owner'"))
        batch_op.drop_index('ix_memberships_user')

    op.drop_table('memberships')
    op.drop_table('invites')
    op.drop_table('hubs')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_household_id'))

    op.drop_table('devices')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('uq_open_alert', postgresql_where=sa.text('resolved_at IS NULL'), sqlite_where=sa.text('resolved_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_alerts_household_id'))

    op.drop_table('alerts')
    op.drop_table('users')
    with op.batch_alter_table('outbox', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_sent_at'))

    op.drop_table('outbox')
    with op.batch_alter_table('hub_enrollments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hub_enrollments_user_code_hash'))

    op.drop_table('hub_enrollments')
    op.drop_table('households')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_household_id'))

    op.drop_table('audit_log')
    # ### end Alembic commands ###
