"""Cloud broker PSK and ACL files, generated from the DB (Server_Specs §10.3).

Written atomically to MC_BROKER_FILES_DIR; the watcher in the broker container
sends SIGHUP so Mosquitto reloads them without dropping connections.
"""

import asyncio
import logging
import os
from pathlib import Path

from sqlalchemy import select

from ..context import AppContext
from ..db.models import Device, Hub

log = logging.getLogger(__name__)

DEVICE_UP = ("status", "telemetry", "event", "cmd/ack", "config/state")
DEVICE_DOWN = ("cmd", "config/desired")


def render(ctx: AppContext, devices: list[Device], hubs: list[Hub]) -> tuple[str, str]:
    psk_lines = []
    for d in devices:
        if d.gateway == "cloud" and d.psk_enc:
            psk_lines.append(f"{d.id}:{ctx.keys.decrypt(d.psk_enc)}")
    for h in hubs:
        psk_lines.append(f"{h.id}:{ctx.keys.decrypt(h.psk_enc)}")

    acl = [
        "# Generated by mc-server from the database. Do not edit.",
        "",
        "# Every device: its own subtree only (mqtt.md §10).",
        *[f"pattern write mc/v1/%u/{s}" for s in DEVICE_UP],
        *[f"pattern read mc/v1/%u/{s}" for s in DEVICE_DOWN],
        "",
        "# The backend on the internal listener: everything.",
        "user mc-backend",
        "topic readwrite mc/#",
        "",
    ]
    by_household: dict[str, list[str]] = {}
    for d in devices:
        if d.gateway == "hub":
            by_household.setdefault(d.household_id, []).append(d.id)
    for h in hubs:
        acl.append(f"# Hub of household {h.household_id} (hub.md §6)")
        acl.append(f"user {h.id}")
        for dev in sorted(by_household.get(h.household_id, [])):
            acl += [f"topic write mc/v1/{dev}/{s}" for s in DEVICE_UP]
            acl += [f"topic read mc/v1/{dev}/{s}" for s in DEVICE_DOWN]
        acl += [
            f"topic write mc/hub/v1/{h.id}/up/#",
            f"topic read mc/hub/v1/{h.id}/down/snapshot",
            f"topic read mc/hub/v1/{h.id}/down/keys",
            "",
        ]
    psk = "".join(line + "\n" for line in psk_lines)
    return psk, "\n".join(acl) + "\n"


def _write_atomic(path: Path, content: str) -> bool:
    if path.exists() and path.read_text() == content:
        return False
    tmp = path.with_suffix(".tmp")
    tmp.write_text(content)
    os.chmod(tmp, 0o640)  # group mcbroker (gid 1883) lets Mosquitto read it
    tmp.replace(path)
    return True


class BrokerFiles:
    def __init__(self, ctx: AppContext, directory: Path | None):
        self.ctx = ctx
        self.dir = directory
        self._pending: asyncio.Task | None = None

    async def regenerate(self) -> None:
        if self.dir is None:
            return
        async with self.ctx.sessionmaker() as s:
            devices = list(await s.scalars(select(Device).where(Device.deleted_at.is_(None))))
            hubs = list(await s.scalars(select(Hub)))
        psk, acl = render(self.ctx, devices, hubs)
        self.dir.mkdir(parents=True, exist_ok=True)
        changed = _write_atomic(self.dir / "psk", psk) | _write_atomic(self.dir / "acl", acl)
        if changed:
            log.info("broker files updated (%d psk entries)", psk.count("\n"))

    def schedule(self) -> None:
        """Debounced regeneration (1 s) after a change."""
        if self.dir is None or (self._pending and not self._pending.done()):
            return

        async def later():
            await asyncio.sleep(1)
            try:
                await self.regenerate()
            except Exception:
                log.exception("broker file generation failed")

        self._pending = asyncio.get_running_loop().create_task(later())
