// Generates lib/app/theme/color_scheme.dart from design/material-theme.json
// (Material Theme Builder export, Design_System.md §2.1).
//
// Run from app/:  dart run tool/gen_color_scheme.dart
import 'dart:convert';
import 'dart:io';

const _roles = {
  // ColorScheme parameter: JSON key
  'primary': 'primary',
  'onPrimary': 'onPrimary',
  'primaryContainer': 'primaryContainer',
  'onPrimaryContainer': 'onPrimaryContainer',
  'primaryFixed': 'primaryFixed',
  'primaryFixedDim': 'primaryFixedDim',
  'onPrimaryFixed': 'onPrimaryFixed',
  'onPrimaryFixedVariant': 'onPrimaryFixedVariant',
  'secondary': 'secondary',
  'onSecondary': 'onSecondary',
  'secondaryContainer': 'secondaryContainer',
  'onSecondaryContainer': 'onSecondaryContainer',
  'secondaryFixed': 'secondaryFixed',
  'secondaryFixedDim': 'secondaryFixedDim',
  'onSecondaryFixed': 'onSecondaryFixed',
  'onSecondaryFixedVariant': 'onSecondaryFixedVariant',
  'tertiary': 'tertiary',
  'onTertiary': 'onTertiary',
  'tertiaryContainer': 'tertiaryContainer',
  'onTertiaryContainer': 'onTertiaryContainer',
  'tertiaryFixed': 'tertiaryFixed',
  'tertiaryFixedDim': 'tertiaryFixedDim',
  'onTertiaryFixed': 'onTertiaryFixed',
  'onTertiaryFixedVariant': 'onTertiaryFixedVariant',
  'error': 'error',
  'onError': 'onError',
  'errorContainer': 'errorContainer',
  'onErrorContainer': 'onErrorContainer',
  'surface': 'surface',
  'onSurface': 'onSurface',
  'surfaceDim': 'surfaceDim',
  'surfaceBright': 'surfaceBright',
  'surfaceContainerLowest': 'surfaceContainerLowest',
  'surfaceContainerLow': 'surfaceContainerLow',
  'surfaceContainer': 'surfaceContainer',
  'surfaceContainerHigh': 'surfaceContainerHigh',
  'surfaceContainerHighest': 'surfaceContainerHighest',
  'onSurfaceVariant': 'onSurfaceVariant',
  'outline': 'outline',
  'outlineVariant': 'outlineVariant',
  'shadow': 'shadow',
  'scrim': 'scrim',
  'inverseSurface': 'inverseSurface',
  'onInverseSurface': 'inverseOnSurface',
  'inversePrimary': 'inversePrimary',
  'surfaceTint': 'surfaceTint',
};

String _camel(String key) =>
    key.replaceAllMapped(RegExp(r'-(\w)'), (m) => m.group(1)!.toUpperCase());

void main() {
  final json =
      jsonDecode(File('design/material-theme.json').readAsStringSync())
          as Map<String, dynamic>;
  final schemes = json['schemes'] as Map<String, dynamic>;
  final out = StringBuffer()
    ..writeln(
      '// GENERATED by tool/gen_color_scheme.dart from design/material-theme.json.',
    )
    ..writeln(
      '// Do not edit by hand — re-export from Material Theme Builder and regenerate.',
    )
    ..writeln("import 'package:flutter/material.dart';")
    ..writeln()
    ..writeln('abstract final class AppColorSchemes {');
  for (final entry in schemes.entries) {
    final values = entry.value as Map<String, dynamic>;
    final dark = entry.key.startsWith('dark');
    out
      ..writeln('  static const ${_camel(entry.key)} = ColorScheme(')
      ..writeln('    brightness: Brightness.${dark ? 'dark' : 'light'},');
    _roles.forEach((param, key) {
      final hex = (values[key] as String).substring(1);
      out.writeln('    $param: Color(0xFF$hex),');
    });
    out
      ..writeln('  );')
      ..writeln();
  }
  out.writeln('}');
  File('lib/app/theme/color_scheme.dart')
    ..createSync(recursive: true)
    ..writeAsStringSync(out.toString());
  stdout.writeln(
    'Wrote lib/app/theme/color_scheme.dart (${schemes.length} schemes)',
  );
}
